development:
  adapter: postgresql
  encoding: unicode
  database: bootcamp_apps_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: bootcamp_apps_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: bootcamp_apps_production
  pool: 5
  host: localhost